[phases.install]
cmds = ["cd fase-2/ejercicios && npm install"]

[phases.build]
cmds = ["cd fase-2/ejercicios && npx prisma generate && npm run build"]

[start]
cmd = "cd fase-2/ejercicios && node -r tsconfig-paths/register dist/fase-2/ejercicios/src/index.js"
