ALTER TABLE "Cliente"
  ADD COLUMN IF NOT EXISTS "widgetNombre"     TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "widgetColor"      TEXT NOT NULL DEFAULT '#2563eb',
  ADD COLUMN IF NOT EXISTS "widgetBienvenida" TEXT NOT NULL DEFAULT '';
